### ISSUE TITLE
Server crashing on startup with version 2.0.0

### ISSUE THREAD

**Issue by Joulanh** [legoatoom/ConnectibleChains#10]
Only mods installed are:

 cloth config 6.1.48-fabric
fabric api 0.46.0+1.18
connectiblechains-2.0.0

heres the crash report:
[latest.log](https://github.com/legoatoom/ConnectibleChains/files/7875466/latest.log)

**Comment by wackoamd1** [comment]
i have the same thing this is not for server only single player works.

**Comment by legoatoom** [comment]
Seems like an issue with some libraries mod. Somewhere the server tries to acces code that only a client has. Needs some further investigation
