### ISSUE TITLE
Chain links do not transfer correctly when used within a structure block

### ISSUE THREAD

**Issue by Arathain** [legoatoom/ConnectibleChains#15]
When saved within a structure block, the chain knot entity saves the original opposite position, however it does not change it to account for the different placement of the structure, thus breaking.

**Comment by legoatoom** [comment]
If this isn't an edge case I don't know what is.

**Comment by Arathain** [comment]
It's perfectly understandable if you don't want to fix it, I can imagine that it'd be quite difficult, if not borderline impossible. If you *were* to fix it, it'd be helpful for using the chains as decoration in custom structures,  which is what I was looking into, but it is ultimately a niche case so, once again, don't worry about it if you don't want to spend your time on it.

**Comment by Qendolin** [comment]
This can be fixed by storing the relative position instead (in the NBT) I think.

**Comment by Qendolin** [comment]
Will be fixed in the upcoming release
