### ISSUE TITLE
[1.18.2] Unexpected crash when trying to assemble ruined portal

### ISSUE THREAD

**Issue by vico93** [legoatoom/ConnectibleChains#19]
I was testing my modpack after updating everything to 1.18.2, in a test map with Large Biomes type, when i find a ruined portal near a forest. When i tried to place obsidians to close the portal this crash happened.

Information:
Minecraft version: 1.18.2
Fabric Loader version: 0.13.3
Fabric API version: 0.48.0+1.18.2
Connectible Chains version: 2.0.1+1.18.1

Crash report: [Here](https://gist.github.com/vico93/d32dd788848ec6d869782039720d1ddf)

**Comment by Qendolin** [comment]
Although 1.18.2 was a minor version change it had quite some breaking changes related to Tags. For now ConnectibleChains is not compatible with 1.18.2
