### ISSUE TITLE
Crash on startup with "Show Me Your Skin!"

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [legoatoom/ConnectibleChains#24]
**MC** 1.19.2
**FAPI** 0.60.0
**ConnectibleChains** 2.1.2
**[Show Me Your Skin!](https://modrinth.com/mod/show-me-your-skin)** 1.3.3

When 2 mods are installed together, the game crashes on startup.

Let me know if the issue needs to be reported to them instead.

Logs: https://gist.github.com/Footage2-Amply-Pounce/f7565fe42f9a56dc2297aef69011d300

**Comment by legoatoom** [comment]
Will be fixed in v2.1.3
