### ISSUE TITLE
Gold chain from Charm is not linkable

### ISSUE THREAD

**Issue by SplendidAlakey** [legoatoom/ConnectibleChains#26]
**MC** 1.19.2
**FAPI** 0.60.0
**ConnectibleChains** 2.1.3
**Charm** 4.2.2

According to the notes of version 2.1.2 there should be support for Charm's gold chain, but the chain is not linkable and doesn't have a tooltip.

![2022-09-11_08 19 15](https://user-images.githubusercontent.com/86702831/189515222-b0ff84ec-7679-4799-80d7-dbfc5030b58b.png)
![2022-09-11_08 19 17](https://user-images.githubusercontent.com/86702831/189515226-81a46b71-3b73-45cd-b3f2-d77696a66365.png)
![2022-09-11_08 19 22](https://user-images.githubusercontent.com/86702831/189515230-89861aa3-1432-484c-9ebd-c4c7e5bf295c.png)

I didn't see anything relevant in the logs, but here it is just in case: https://gist.github.com/SplendidAlakey/cd8223b4b3db1c47d236a55e6eafa021

**Comment by legoatoom** [comment]
that is weird. let me check

**Comment by legoatoom** [comment]
I think I have found the problem. Will probably fixed next version.
Can't check it though since for some reason charm doesn't want to run in my developer environment.

**Comment by Footage2-Amply-Pounce** [comment]
I could check it if you upload the build here.

**Comment by StunnerPony** [comment]
Was having the same issue so I downloaded the code and realized the problem was that it's looking for a "charm:golden_chain" identifier, when Charm calls it "charm:gold_chain". It's really just a simple typo on the BuiltinCompat.java file
Once I changed that and built the mod again it works flawlessly.
