### ISSUE TITLE
[Feature Request] Mythic Metals Decorations Compatibility 

### ISSUE THREAD

**Issue by JannekeJairia** [legoatoom/ConnectibleChains#29]
Hi! 

Love the mod! On the curseforge page it says you're thinking of adding other mod compatibility. 
The mythic metals decorations mod has a lot of chains that I love using, and would love it if you could add functionality for them :)! 
[Mythic Metals Decorations](https://www.curseforge.com/minecraft/mc-mods/mythicmetals-decorations)

Let me know if there is anything I can do to help!
-Knitty

**Comment by legoatoom** [comment]
#21 Was already asked and implemented. Is it not working correctly?

**Comment by JannekeJairia** [comment]
No, but I am running the 1.18.2 version. 
Maybe that's why?

**Comment by legoatoom** [comment]
I might look into it. I also have some ideas of making it possible for anyone to add their own compatibility.

**Comment by JannekeJairia** [comment]
That would be awesome!

**Comment by legoatoom** [comment]
Implemented in 2.1.4
