### ISSUE TITLE
Crash when playing

### ISSUE THREAD

**Issue by YumatanGames** [legoatoom/ConnectibleChains#3]
Hi, I have a crash and this mod was tagged as responsible by Not Enough Crashes. 

Here's the crash log:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/25/21 10:45 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.6)
	at com.github.legoatoom.connectiblechains.client.render.entity.ChainKnotEntityRenderer.createChainLine(ChainKnotEntityRenderer.java:108)
	at com.github.legoatoom.connectiblechains.client.render.entity.ChainKnotEntityRenderer.render(ChainKnotEntityRenderer.java:88)
	at com.github.legoatoom.connectiblechains.client.render.entity.ChainKnotEntityRenderer.render(ChainKnotEntityRenderer.java:57)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:261)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1459)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1219)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being rendered --
Details:
	Entity Type: connectiblechains:chain_knot (com.github.legoatoom.connectiblechains.enitity.ChainKnotEntity)
	Entity ID: 17825
	Entity Name: Chain Knot
	Entity's Exact location: -64.50, 64.50, -1551.50
	Entity's Block location: World: (-65,64,-1552), Chunk: (at 15,4,0 in -5,-97; contains blocks -80,0,-1552 to -65,255,-1537), Region: (-1,-4; contains chunks -32,-128 to -1,-97, blocks -512,0,-2048 to -1,255,-1537)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	Entity NBT: {FallDistance:0.0f,Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],OnGround:0b,Air:300s,Pos:[-64.5d,64.5d,-1551.5d],Fire:-1s,UUID:[I;-1464610250,1076380500,-1858119159,215456131],PortalCooldown:0,Invulnerable:0b}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:283)
	at net.minecraft.class_761.method_22977(class_761.java:1459)
	at net.minecraft.class_761.method_22710(class_761.java:1219)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
-- Renderer details --
Details:
	Assigned renderer: com.github.legoatoom.connectiblechains.client.render.entity.ChainKnotEntityRenderer@34862de1
	Location: -1.04,-1.18,2.64 - World: (-2,-2,2), Chunk: (at 14,-1,2 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 0.0
	Delta: 0.12007999
-- Affected level --
Details:
	All players: 1 total; [class_746['Yumatan'/126, l='ClientLevel', x=-63.46, y=64.06, z=-1554.14]]
	Chunk stats: SodiumChunkCache: 4095
	Level dimension: minecraft:overworld
	Level spawn location: World: (185,64,-174), Chunk: (at 9,4,2 in 11,-11; contains blocks 176,0,-176 to 191,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 162239 game time, 190642 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 819402480 bytes (781 MB) / 3757572096 bytes (3583 MB) up to 9320792064 bytes (8889 MB)
	CPUs: 16
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2000m -Xmx10000m
	Suspected Mods: Fabric Loader (fabricloader), Connectible Chains (connectiblechains)
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.9
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		antiautojump: Anti Auto Jump 1.1
		antighost: AntiGhost 1.16.5-fabric0.30.0-1.1.3
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.8.130
		artifice: Artifice 0.14.6+1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bebooks: Better Enchanted Books 1.2.6
		better_wandering_trader: Better Wandering Trader 1.6.2
		betterbeds: Better Beds 1.1.0
		betterbiomeblend: Better Biome Blend 1.16.4-1.1.2-fabric
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		betterthanmending: BetterThanMending 1.2.0
		brokennametags: Broken Name Tags 1.0.0
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cherishedworlds: Cherished Worlds 1.2.0-1.16.3
		classicalart: Classical Art 1.0.0
		climbladdersfast: ClimbLaddersFast 1.1.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.14
		colormatic: Colormatic 2.2.8+mc.1.16.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.1-1.16.4
		connectiblechains: Connectible Chains 1.2.0
		continuebutton: Continue Button 1.0.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		couplings: Couplings 1.3.3
		crowdin-translate: CrowdinTranslate 1.2
		cullleaves: Cull Leaves 2.1.0
		custom-fog: Custom Fog 1.4.0
		darkpaintings: Dark Paintings 1.0.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dontdropit: Don't Drop It! 2.2.1+1.16
		dreamrng: Dream RNG 1.0.0
		dynamicfps: Dynamic FPS 2.0.1
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		editsign: Edit Sign 2.2.0
		entityculling: EntityCulling-Fabric 1.2.1
		fabric: Fabric API 0.31.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fabrishot: Fabrishot 1.3.0
		fairenchanting: FairEnchanting 1.2.0
		fallingleaves: Falling Leaves 1.5.0+1.16.5
		fastbench: FastBench 2.3
		fastchest: FastChest 1.2+1.16
		fastfurnace: FastFurnace 2.3
		fatxporbs: Fat Experience Orbs 0.0.7
		fiber: fiber 0.23.0-2
		howlingwolves: Howling Wolves 1.0.0+build.1
		hydrogen: Hydrogen 0.2
		illuminations: Illuminations 1.5
		infinityfix: Infinity Fix 1.1.0
		inventoryprofiles: Inventory Profiles 0.4.2
		invisframes: Invisible Frames 2.0.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kirin: Kirin UI 1.7-1.16.2
		krypton: Krypton 0.1.2
		lambdynlights: LambDynamicLights 1.3.4+1.16
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		leafmealone: Leaf Me Alone 2.1
		lionutils: LionUtils 7.0.0+1.16
		lithium: Lithium 0.6.4
		mambience: MAmbience 2.1.0+1.16.4
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.16.8
		morepaths: More Paths 0.0.3
		mostructures: Mo' Structures 1.1.0+mc.1.16.5
		multi_item_lin: Multi Item Lin 1.0.0
		musicdr: Music Duration Reducer 1.2.0
		netherite_plus: Netherite Plus Mod 1.3.8-1.16.5
		nofade: No Fade 1.16.5-1.0.1
		notenoughcrashes: Not Enough Crashes 3.1.8
		npcvariety: NPC Variety 1.0.1
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		olifantenpad: Olifantenpad 1.0.0
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		oro_config: OroArmor Config unspecified
		paintingcycle: Painting Cycle 1.0.0
		phosphor: Phosphor 0.7.1+build.11
		presencefootsteps: Presence Footsteps r29+1.16.4
		raisedclouds: Raised Clouds 1.0.0
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		replaymod: Replay Mod 1.16.4-2.5.1
		riverredux: River Redux 0.1.6
		rocks: This Rocks! 1.3.1
		roughlyenoughitems: Roughly Enough Items 5.8.10
		roughlyenoughitems-api: REI (API) 5.8.10
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
		roughlyenoughitems-runtime: REI (Runtime) 5.8.10
		seamless_loading_screen: Seamless Loading Screen 1.3.3
		simplexterrain: Simplex Terrain 0.7.2
		slight-gui-modifications: 'Slight' GUI Modifications 1.7.1
		smoothboot: Smooth Boot 1.16.5-1.5.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sodium: Sodium 0.1.0
		sodium-extra: Sodium Extra 0.2.2
		somnus: Somnus API 0.0.10-1.16.4
		spruceui: SpruceUI 2.0.4+1.16
		stoneholm: Stoneholm 1.1.0
		umollu_ash: ASH - Another Simple HUD 1.1.13
		vafoen: Vanilla Food Enhanced 1.1.1
		villagernames: Villager Names 1.6.0
		wandering_collector: Wandering Collector 1.0.0+mc1.16.5
		wildworld: Wild World 2.0.0+1.16.5
		wthit: wthit 2.4.0+1.16.5
		xaerominimap: Xaero's Minimap 21.7.0
		xaeroworldmap: Xaero's World Map 1.13.3
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.11, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: vanilla, replaymod_lang (incompatible), Fabric Mods, file/Nautilus3D_V1.4_[1.13+].zip, cullleaves/smartleaves, slightguimodifications:cts_textures, betterbeds/connectedbeds, betterbeds/fancybeds, file/immersive-soundscapes-resources-v2.4.zip
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0

**Comment by legoatoom** [comment]
I tried fixing it, although if it happens again, create a new issue.
