### ISSUE TITLE
In multiplayer chains that exist in multiple chunks break

### ISSUE THREAD

**Issue by joonas-erho** [legoatoom/ConnectibleChains#31]
Hello, I am running a 1.18.2 Fabric server and sometimes chains that exist within more than one chunk disappear. I'm guessing this has something to do with only one of the chunks loading and this breaking the chain?

**Comment by Qendolin** [comment]
I cannot recreate this issue, could you upload a world that we can take a look at. -
Also what is your configured "Max Chain Distance"?

**Comment by 909oce** [comment]
Happens to me aswell, chains that cross chunk boundaries have a chance to break, unsure how to reproduce exactly but every now and then I notice a chain missing.

**Comment by Qendolin** [comment]
That would explain why I couldn't recreate the issue. Which relevant mods do you have installed?

**Comment by r632** [comment]
I reduced to a minimum + those that I no longer know:

animatica-0.4+1.18.jar 
c2me-fabric-mc1.18.2-0.2.0+alpha.7.38.jar 
cc-restitched-1.100.8.jar 
cem-0.7.1.jar 
Clumps-fabric-1.18.2-8.0.0+17.jar 
collective-1.18.2-7.7.jar 
completeconfig-lib-1.4.1.jar 
continuity-2.0.1+1.18.2.jar 
cullleaves-2.3.2.jar 
CullLessLeaves-1.0.1.jar 
debugify-1.11.0-fabric-1.18.2.jar 
DisplayCase-fabric-1.18.2-1.0.3.jar 
dynamic-fps-3.3.3+minecraft-1.16.5.jar 
enhancedblockentities-0.6+1.18.2.jar 
entity-texture-features-3.0.4-mc1.18.x.jar 
entityculling-fabric-mc1.18-1.5.1.jar 
etched-fabric-2.2.1+1.18.2.jar 
fabric-api-0.76.0+1.18.2.jar 
fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar 
fabrictailor-1.9.0+1.18.2.jar 
fabrishot-1.7.0.jar 
farsight.fabric-1.18-1.9.jar.disabled 
Fastload+1.18.2-1.5.10.jar 
homabric-2.0.0.jar 
indium-1.0.7+mc1.18.2.jar 
iris-mc1.18.2-1.6.11.jar 
item-model-fix-1.0.3+1.18.jar 
Jade-1.18.2-fabric-5.100.0.jar 
lambdabettergrass-1.2.3+1.18.jar 
lambdynamiclights-2.1.0+1.17.jar 
lazydfu-0.1.2.jar 
leashmod-1.0.5.jar 
lithium-fabric-mc1.18.2-0.10.3.jar 
Measurements-fabric-1.18.2-1.3.1.jar 
memoryleakfix-fabric-1.17+-1.1.2.jar 
midnightlib-0.4.4.jar 
mixintrace-1.1.11.17.jar 
nofade-1.18-2.0.1.jar 
notenoughanimations-fabric-1.7.0-mc1.18.2.jar 
observable-2.2.3-fabric.jar 
optigui-2.0.0-alpha.4.jar 
Patchouli-1.18.2-71.1-FABRIC.jar 
Pehkui-3.7.12+1.14.4-1.20.4.jar 
phonos-0.31.18.2.jar 
pollen-fabric-1.6.1+1.18.2.jar 
polymer-all-0.2.0-rc.4.8+1.18.2.jar 
polysit-0.0.2+mc.1.18.2.jar 
puzzle-1.4.1-1.18.jar 
reeses_sodium_options-1.4.3+mc1.18.2-build.42.jar 
Rrls-1.18.2-3.1.0-fabric.jar 
servercore-1.2.9-1.18.2.jar 
Slideshow-fabric-1.18.2-1.0.2-hotfix-1.jar 
slight-gui-modifications-2.1.0.jar 
smoothboot-fabric-1.18.2-1.7.0.jar 
sodium-extra-0.4.17+mc1.18.2-build.94.jar 
sodium-fabric-mc1.18.2-0.4.1+build.15.jar 
starlight-1.0.2+fabric.89b8d9f.jar 
taterzens-1.8.5-fabric.jar 
TieFix-1.9.0.jar 
tooltipfix-1.0.4-1.18.jar 
trinkets-3.3.1.jar 
vmp-fabric-mc1.18.2-0.2.0+beta.3.126-all.jar 
webstreamer-1.2.3.jar 
windchimes-1.2.0.jar 
yosbr-0.1.1.jar 



if you want the entire list:

3dskinlayers-fabric-1.5.2-mc1.18.2.jar 
Adorn-3.5.0+1.18.2-fabric.jar 
advancementinfo-1.18.2-fabric0.47.10-1.3.1.jar 
animatica-0.4+1.18.jar 
another_furniture-fabric-1.2.2-1.18.2.jar 
antighost-1.18.2-fabric0.47.10-1.1.4.jar 
appleskin-fabric-mc1.18.2-2.4.1.jar 
architectury-4.11.93-fabric.jar 
arrp-0.5.7.jar 
automobility-0.3+1.18.2.jar 
badpackets-fabric-0.1.3.jar 
bettercombat-fabric-1.5.5+1.18.2.jar 
bettermounthud-1.1.4.jar 
better_climbing-1.1.0-FABRIC.jar 
borderless-mining-1.1.2+1.18.2.jar 
c2me-fabric-mc1.18.2-0.2.0+alpha.7.38.jar 
campanion-3.0.4.jar 
camsbackpacks-2.2.jar 
Capes-1.3.1+1.18.2.jar 
cc-restitched-1.100.8.jar 
cem-0.7.1.jar 
chisel-1.4.51.18.2.jar 
ChiselsBits-fabric-1.18.2-1.2.116.jar 
CITResewn-1.0.1+1.18.2.jar 
classicombat-1.0.5-1.18.2.jar 
cloth-api-3.2.64.jar 
cloth-config-6.5.102-fabric.jar 
Clumps-fabric-1.18.2-8.0.0+17.jar 
collective-1.18.2-7.7.jar 
completeconfig-lib-1.4.1.jar 
connectiblechains-2.1.4+1.18.2.jar 
continuity-2.0.1+1.18.2.jar 
cullleaves-2.3.2.jar 
CullLessLeaves-1.0.1.jar 
debugify-1.11.0-fabric-1.18.2.jar 
decorative-4.2.0.jar 
disguiselib-1.2.2-fabric.jar 
DisplayCase-fabric-1.18.2-1.0.3.jar 
DistantHorizons-2.0.1-a-1.18.2.jar 
do-a-barrel-roll-2.6.2+1.18.2-fabric.jar 
doubledoors-1.18.2-5.1.jar 
dwayne-the-block-johnson-2.1.1.jar 
dynamic-fps-3.3.3+minecraft-1.16.5.jar 
EditSign-1.18.2-2.3.1.jar 
elytratrinket-fabric-3.0.0-1.18.1.jar 
emotecraft-for-MC1.18.2-2.2.7-b.build.50-fabric.jar 
enhancedblockentities-0.6+1.18.2.jar 
entity-texture-features-3.0.4-mc1.18.x.jar 
entityculling-fabric-mc1.18-1.5.1.jar 
etched-fabric-2.2.1+1.18.2.jar 
extractinator-fabric-1.18.2-2.0.1.jar 
fabric-api-0.76.0+1.18.2.jar 
fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar 
fabrictailor-1.9.0+1.18.2.jar 
fabrishot-1.7.0.jar 
factory-blocks-mod-1.0.01.18.2.jar 
farsight.fabric-1.18-1.9.jar.disabled 
Fastload+1.18.2-1.5.10.jar 
ferritecore-4.2.1-fabric.jar 
firstperson-fabric-2.2.2-mc1.18.2.jar 
freecam-fabric-modrinth-1.1.9+1.18.jar 
geckolib-fabric-1.18-3.0.80.jar 
gmod-title-screen-1.1+1.18.jar 
graves-2.0.3+1.18.2.jar 
headindex-1.0.8-1.18.2.jar 
held-item-info-1.4.2+1.18.jar 
homabric-2.0.0.jar 
HWGMod-1.18.2-1.1.12.jar 
iammusicplayer-fabric-1.18.2-3.16.5.jar 
image2map-0.2.2.jar 
immersive_aircraft-0.5.21.18.2-fabric.jar 
immersive_paintings-0.6.71.18.2-fabric.jar 
indium-1.0.7+mc1.18.2.jar 
infinitybuttons-4.0.1-mc1.18.2.jar 
iris-mc1.18.2-1.6.11.jar 
item-model-fix-1.0.3+1.18.jar 
Jade-1.18.2-fabric-5.100.0.jar 
journeymap-1.18.2-5.9.2-fabric.jar 
lambdabettergrass-1.2.3+1.18.jar 
lambdynamiclights-2.1.0+1.17.jar 
language-reload-1.2.1.jar 
lanterns-belong-on-walls-1.3.0-1.18.x.jar 
lazydfu-0.1.2.jar 
leashmod-1.0.5.jar 
libIPN-fabric-1.18.2-2.0.2.jar 
lithium-fabric-mc1.18.2-0.10.3.jar 
mcw-doors-1.1.0fabric-mc1.18.2.jar 
mcw-furniture-3.2.2-mc1.18.2fabric.jar 
mcxr-core-0.2.1.jar 
Measurements-fabric-1.18.2-1.3.1.jar 
memoryleakfix-fabric-1.17+-1.1.2.jar 
midnightlib-0.4.4.jar 
mixintrace-1.1.11.17.jar 
Modern-Elevators-Escalators-fabric-1.18.2-3.1.6.jar 
modmenu-3.2.5.jar 
morechathistory-1.18-1.1.0.jar 
moreredlamps-0.0.2-1.18.jar 
MTR-fabric-1.18.2-3.2.2-hotfix-1.jar 
MTR-NTE-0.4.21.18.2.jar 
nicemod-1.2 - 1.18.2.jar 
nofade-1.18-2.0.1.jar 
notenoughanimations-fabric-1.7.0-mc1.18.2.jar 
observable-2.2.3-fabric.jar 
optigui-2.0.0-alpha.4.jar 
otyacraftengine-fabric-1.18.2-2.14 (1).jar 
paladin-furniture-mod-1.2.1-fabric-mc1.18.2.jar 
Patchouli-1.18.2-71.1-FABRIC.jar 
Pehkui-3.7.12+1.14.4-1.20.4.jar 
phonos-0.31.18.2.jar 
Pick-Block-Pro-1.5.11-mc1.18.2.jar 
Ping-Wheel-1.7.1-fabric-1.18.2.jar 
plantinajar-2.3.1.jar 
plasmovoice-fabric-1.18-1.2.19.jar 
player-animation-lib-fabric-0.4.2+1.18.jar 
polaroidcamera-1.2.9.jar 
pollen-fabric-1.6.1+1.18.2.jar 
polymer-all-0.2.0-rc.4.8+1.18.2.jar 
polysit-0.0.2+mc.1.18.2.jar 
PresenceFootsteps-1.5.1.jar 
puzzle-1.4.1-1.18.jar 
reeses_sodium_options-1.4.3+mc1.18.2-build.42.jar 
RoughlyEnoughItems-8.3.681-fabric.jar 
Rrls-1.18.2-3.1.0-fabric.jar 
servercore-1.2.9-1.18.2.jar 
ShowMeWhatYouGot-1.18-1.0.1.jar 
sidekick-fabric-2.0.51.18.2.jar 
Slideshow-fabric-1.18.2-1.0.2-hotfix-1.jar 
slight-gui-modifications-2.1.0.jar 
slotlock-1.1.1-BETA+1.18.jar 
smoothboot-fabric-1.18.2-1.7.0.jar 
sodium-extra-0.4.17+mc1.18.2-build.94.jar 
sodium-fabric-mc1.18.2-0.4.1+build.15.jar 
sound_track-1.0.7.jar 
starlight-1.0.2+fabric.89b8d9f.jar 
super-secret-revival-1.3+1.18.jar 
tabtps-fabric-mc1.18.2-1.3.13.jar 
taterzens-1.8.5-fabric.jar 
tempad-fabric-1.18.2-1.4.1.jar 
TieFix-1.9.0.jar 
tooltipfix-1.0.4-1.18.jar 
trank_o_mat-fabric-1.18.2-1.2.0.jar 
trashcans-0.0.2-1.18.X.jar 
trinkets-3.3.1.jar 
vanish-1.1.0.jar 
vmp-fabric-mc1.18.2-0.2.0+beta.3.126-all.jar 
webstreamer-1.2.3.jar 
windchimes-1.2.0.jar 
wired-redstone-0.3.10+1.18.2.jar 
worldedit-mod-7.2.10.jar 
yosbr-0.1.1.jar 
Zoomify-1.6.0.jar 
[1.18]+fabric-pigeonpost-3.0.0.jar

**Comment by legoatoom** [comment]
Unfortunately, this issue is getting quite old now. And the issue was created for mc 1.18.x.
I do not support this version any more.
Unless this still applies in the latest version of this mod, this issue will be closed.
