### ISSUE TITLE
[Version Request] Minecraft 1.19 - 1.19.1

### ISSUE THREAD

**Issue by mateodoks** [legoatoom/ConnectibleChains#32]
will u make it campatible with 1.19.

**Comment by legoatoom** [comment]
I do not see why you would need 1.19 so badly? 1.19.2 is the dominant version, as is 1.18.2.

**Comment by legoatoom** [comment]
In the latest version there is no restriction to try it out in 1.19 and 1.19.1. I assume there are no problems but if so, comment here.
