### ISSUE TITLE
[Feature Request] Chain Render Distance Config

### ISSUE THREAD

**Issue by JLUsr** [legoatoom/ConnectibleChains#33]
A request to add an option to the config to adjust the render distance for chains. I personally enjoy using [Block Entity Extended Rendering](https://modrinth.com/mod/beer) and thought it might be nice if I could also extend the range at which chains render. This might also help some who have similar issues as mentioned in #22, without having to impact those who do not wish to see an increase in range.

**Comment by kaolincash** [comment]
I'd also very much like this feature, as I'm trying to view my build from more than an inch away and the chains just all vanish 😅

**Comment by legoatoom** [comment]
The value I set it to was pretty short yes. How about the default, which 5 chunks?
I cannot make the mod you provided work with this mod since that mod works with block-entities. The chain is not a block-entity.

**Comment by legoatoom** [comment]
v2.4.0 has increased the view distance to be equal to how far you can see chests.
I hope this suffices.
