### ISSUE TITLE
[Feature Request] Rename to adjust chain hang/drip amount

### ISSUE THREAD

**Issue by JLUsr** [legoatoom/ConnectibleChains#36]
Something along the lines of renaming a chain in an anvil or right-clicking a knot entity with a nametag to alter the hang amount applied to that specific chain/chains tied to that specific knot entity.

E.g. You take a chain and rename it to `20.0` thus adjusting the `Chain Drip` value for that specific chain to `20.0`.
This would allow for a longer chain connection that still looks relatively taut without making all of the other chains you've placed look like they don't have any drip/hang. This could also be used in reverse to allow for some large hangs in chains of short distances without having to sacrifice normal use for a mostly niche design aspect.

**Comment by Qendolin** [comment]
I like the idea but I don't think renaming the item is a good solution, it presents too many issues. Maybe a configuration item would be better. 
I would suggest using a vanilla item to configure the chain length. You would set the hang value by interacting with an existing chain and it would remember it for all following chains that you place.

**Comment by legoatoom** [comment]
Unfortunately, this goes _way_ beyond the scope of this mod.
