### ISSUE TITLE
Inconsistent crash when being near connected chains

### ISSUE THREAD

**Issue by SplendidAlakey** [legoatoom/ConnectibleChains#39]
**MC** 1.19.2
**[QFAPI](https://modrinth.com/mod/qsl)** 4.0.0-beta.22
**ConnectibleChains** 2.1.4

Not sure how to reproduce it, as it's very inconsistent, but I'm hoping you could at least point me in the right direction after seeing the logs. I have a test world with a bunch of stuff in it, including a few connected chains. Randomly, my game just crashes and I can see ConnectibleChains mentioned in the trace.

Logs: https://gist.github.com/SplendidAlakey/02f6457e41490770b47dafd81c8b3544#file-crash-log; https://gist.github.com/SplendidAlakey/02f6457e41490770b47dafd81c8b3544#file-latest-log (yes, it's a big modpack, but, again, hoping that the logs would at least point me in the right direction, as binary searching such an inconsistent crash is going to take ages...)

**Comment by SplendidAlakey** [comment]
Hey, just a quick update: I haven't come across this crash since I reported it. I've been using the same exact world and the only things that changed was me updating all my mods. As such, I will probably close this issue in a few days, if I don't get another crash again.

**Comment by legoatoom** [comment]
dammit my strategy of waiting didn't work...

**Comment by SplendidAlakey** [comment]
Haha, yeah, sorry. I don't know what else to add to this report, to be honest. It's very annoying when there's no way to consistently reproduce a bug... I can play for hours with no issues or crash seconds after opening the world. In worlds, where I haven't placed any connected chains it doesn't happen, though.

**Comment by legoatoom** [comment]
Especially when it is `java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1792.method_40131()" because the return value of "net.minecraft.class_1799.method_7909()" is null` is the crash.

Ahh yes!  I remember what `class_1799.method_7909()` is! I totally understand this issue now.

**Comment by SplendidAlakey** [comment]
I might be onto something here. I've been placing a bunch of connected chains in my test worlds and, to my surprise, they broke! But not in a sense, that something went wrong, no, they just popped off. Specifically, when I intertwine them over each other. That does not happen in the world, that crashes. Since crash logs mention chain entity collision.. makes me think something prevents it from breaking and it crashes instead. However, connected chains don't just pop off, if you intertwine them, you need to re-log into the world, so I assume that's not intended to begin with?

I'll be testing it more in the future, will let you know if I discover anything else. Best case scenario my older test worlds are just corrupted somehow.

**Comment by legoatoom** [comment]
> Best case scenario my older test worlds are just corrupted somehow.
Well.. if you know where the error is, you could always use mcedit to remove chunks. 
That way you don't loose the whole world.

**Comment by SplendidAlakey** [comment]
It's a superflat test ground, so I don't care about saving it. As long as the crash is not reproducible during normal gameplay, I'll just close this issue. My logs are way too big to get anything useful out of them and the `class_1799.method_7909()` translates to `net/minecraft/world/item/ItemStack::getItem`, which also tells me nothing. I'll keep it open for a few more days, in case I do encounter a crash in newer worlds, but unless I can collect some actually useful information about the crash, I don't think there's much to do here.

**Comment by SplendidAlakey** [comment]
Yeah, I'm closing this. It doesn't seem to crash on newer worlds, so I assume something got corrupted in my old one. In any case without concrete steps to reproduce this and coherent logs, there's not much to be done, so I'm closing this.
