### ISSUE TITLE
Chains are invisible.

### ISSUE THREAD

**Issue by TheSourOnion** [legoatoom/ConnectibleChains#4]
Chains are invisible with sildurs shaders and maybe others too. The knot is there and the shadows, but not the chain itself.

**Comment by leon7104** [comment]
im gonna delete this mod huh

**Comment by TheSourOnion** [comment]
How come you wont fix it?

**Comment by leon7104** [comment]
he don't know how to fix, so just let it go.

**Comment by legoatoom** [comment]
Yes, I do not know how to fix this issue.
I do wonder if leads are visible in that shader, since the chain works similarly.
If they are also invisible, then it is an issue with the shaders.

**Comment by TheSnowyChickens** [comment]
Hello,
before I open a new issue with the topic "invisible chains", I better ask if this:
![grafik](https://user-images.githubusercontent.com/29357962/193319821-1f769a91-1dde-4335-a23b-064c81d3c88f.png)

is maybe the "same" bug like the one from Onion ?
(in my case it's not a shader thing and not Sodium or Optifine)

1.19.2, fabric 0.14.9, CC 2.1.3

**Comment by TheSourOnion** [comment]
If you have a mod installed or a certain resource pack on, that could break it. If you don't, then I don't know since mine broke when I used optifine of sodium.
