### ISSUE TITLE
[Feature Request] Connectible chain play same sound as chain

### ISSUE THREAD

**Issue by zeid0ne** [legoatoom/ConnectibleChains#41]
Hi, with PresenceFootsteps mod, walking on or against chain play a sound.
Is it possible to do the same with the connectible chain ?
Thanks

**Comment by legoatoom** [comment]
I looked into this, entities do not have a sound when they are walked on. (Shulkers for example) 
I cannot easily add this, I tried using collision but that resulted in a constant sound. 
So at the moment, I do not see how I can _easily_ implement this.
