### ISSUE TITLE
[Feature Request] Chains Connect Blocks

### ISSUE THREAD

**Issue by vico93** [legoatoom/ConnectibleChains#45]
![image](https://user-images.githubusercontent.com/3485505/232581500-326e068f-fb86-419d-a40e-922d562fac99.png)

Like the image shows, allow chains to connect not only fences/walls, but also other blocks replicating said Quark feature.
Since there's no Quark for Fabric, that would greatly benefit Fabric players.

**Comment by legoatoom** [comment]
This feature request is out of scope of this mod. Sorry.
