### ISSUE TITLE
Chains invisible when rejoining a server

### ISSUE THREAD

**Issue by Jacksteroonie** [legoatoom/ConnectibleChains#47]
Whenever I rejoin a server in which I have placed the connectible chains, they are invisible. They can still be interacted with, preventing movement and are able to be cut with shears. The chain wrapped around the fence is still visible. The chain spanning between the fences is invisible.

**Comment by legoatoom** [comment]
Could you provide a step by step guide for me to reproduce the bug?

**Comment by DudBoii123** [comment]
> Could you provide a step by step guide for me to reproduce the bug?

all you have to do is play on a multiplayer server, connect two fences (say 4 blocks apart) with a chain, leave the server, and rejoin. Sometimes it takes leaving/joining 2 or 3 times, but it always happens.

**Comment by legoatoom** [comment]
I will take a look at it when I have time.

**Comment by genorfake** [comment]
> I will take a look at it when I have time.

hi, legoatoom. it seems like this bug happens in single player worlds too. placecing new chains on fences and rejoining fixes the bugged chains and makes the new chains invisible. here are the steps i took to do the bug: place 2 fences with any distance between and put a chain on them. rejoin the world and  you got invisible chains

**Comment by FAKHORII** [comment]
> > I will take a look at it when I have time.
> 
> hi, legoatoom. it seems like this bug happens in single player worlds too. placing new chains on fences and rejoining fixes the bugged chains and makes the new chains invisible. here are the steps i took to do the bug: place 2 fences with any distance between and put a chain on them. rejoin the world and you got invisible chains. this issue also may have to do something with sodium or the simply optimized modpack im not sure though

same with me, u just join ur world and u find it invisible, simple as that

**Comment by Dbl7id** [comment]
Possible this was due to an older version of sodium. Updating to the latest version should remove this issue entirely.

**Comment by legoatoom** [comment]
If this issue remains, please let me know.

**Comment by FAKHORII** [comment]
I believe it happens only if u are in range with the chains, if u go far where they don't render usually and come closer again then they will appear, but hey! why the range of rendering the chains is sooo short anyway??
I made a bridge that is a somewhat of a couple of chunks and the chains wont render further like!... it doesn't make things look good!
plus it drops the fps like crazy

**Comment by legoatoom** [comment]
> I believe it happens only if u are in range with the chains, if u go far where they don't render usually and come closer again then they will appear, but hey! why the range of rendering the chains is sooo short anyway?? I made a bridge that is a somewhat of a couple of chunks and the chains wont render further like!... it doesn't make things look good! plus it drops the fps like crazy

I can make the range increase, that is something I will do for the next update.
So you also have issues like #52?

**Comment by FAKHORII** [comment]
> > I believe it happens only if u are in range with the chains, if u go far where they don't render usually and come closer again then they will appear, but hey! why the range of rendering the chains is sooo short anyway?? I made a bridge that is a somewhat of a couple of chunks and the chains wont render further like!... it doesn't make things look good! plus it drops the fps like crazy
> 
> I can make the range increase, that is something I will do for the next update. So you also have issues like #52?

I really cant tell, all I know I made a long bridge.. something like 40 blocks with chains in 2 sides and it drops fps by a lot
as if there are a hundred entity in front of me... idk anything about such stuff, but cant the chains just act like normal blocks somehow! instead of like entities...
anyways, ty for ur care and also for increasing the range of the render, appreciate u <3

**Comment by legoatoom** [comment]
40? The default is set to 7. 
40 blocks will create a lot of collision entities.

**Comment by Learwin** [comment]
I also get the issue that chains disappear on world reload. Not always but I would say 50/50.
![grafik](https://github.com/legoatoom/ConnectibleChains/assets/6223515/1afdcdf6-497b-45d5-a303-1feb123499f8)

Going away for like 30-50 blocks and returning makes them show up again.
![grafik](https://github.com/legoatoom/ConnectibleChains/assets/6223515/be36b954-13f6-46ef-8c4e-6c7a47374976)

In addition I noticed that this appears in the console
```
[16:09:43] [Render thread/WARN] [ConnectibleChains/]: Tried to attach from null (#2086) which is not chain knot
[16:09:43] [Render thread/WARN] [ConnectibleChains/]: Tried to attach from null (#2105) which is not chain knot
[16:09:43] [Render thread/WARN] [ConnectibleChains/]: Tried to attach from null (#2131) which is not chain knot
```

**Comment by legoatoom** [comment]
I have done some changes to the networking in `1.20.4` Please keep me up to date if it still happens.

**Comment by Leobizaz** [comment]
Hello! This issue still persists on 1.20.1
I'm running on the latest (as of now) 1.20.1 Sodium 0.5.8

**Comment by Leobizaz** [comment]
Also, weirdly enough after respawning (on singleplayer) the chains loaded back up normally.

**Comment by legoatoom** [comment]
Yes the problem is simple, the info to attach a chain from point a to point b arrives before the client knows about point a.
Thus when I try to get the entity from an ID the client is like, "i dunno what that entity is" and returns null.

Can you check if the problem still exists in <code>1.20.**4**</code>  because I tried to fix this exact problem then.

**Comment by legoatoom** [comment]
Due to inactivity, this issue is assumed to be fixed.
