### ISSUE TITLE
No 1.20?

### ISSUE THREAD

**Issue by Mahadbaloch** [legoatoom/ConnectibleChains#51]
Mod directly went to 1.20.1

So no 1.20?

**Comment by legoatoom** [comment]
1.20.1 was a hotfix. This means you should not play on 1.20 at all.

**Comment by Mahadbaloch** [comment]
Many mods dont update to 1.20.1 so that 🤷 often I see just update jumps, like you going directly to 1.20.1, there will be people directly going from 1.20 to .2 or something. Or just slow updating

**Comment by legoatoom** [comment]
Many mods work if multiple versions, but in this case I specified specifically that you need to be on 1.20.1 to play.
See this file, where I specified the dependencies.

https://github.com/legoatoom/ConnectibleChains/blob/e86bbc4f4636e541a80c34099e0885ee99d6f793/src/main/resources/fabric.mod.json#L37-L42

You could _technically_ alter the `.jar` file to make this say `1.20.0` or `>=1.20.0` and try it out if you want.
But I did not test this or guaranty anything working.
