### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by 909oce** [legoatoom/ConnectibleChains#52]
Hi, I've recently added some chains to my world and I've noticed when I'm in render distance of them my GPU gets bottlenecked to shit by CPU.

AMD Ryzen 7 5700X 8-Core and RTX 4070.

I have about 15 chains, which cause me to drop to 30% GPU usage.

Is there some way to optimize the amount of CPU required for the chains or settings I can change to fix this?

**Comment by legoatoom** [comment]
I tried some profiling (F3+L) to test if there is a problem here.
I did not find any significant increase in the CPU usage.

I would like to know this:
- A List of mods you are using.
- If you are using shaders. If so, does changing shaders alter this.
- Are the chains long or short?
- Server or Singleplayer?
