### ISSUE TITLE
[Version Request] 1.20.4 update

### ISSUE THREAD

**Issue by vico93** [legoatoom/ConnectibleChains#55]
Is a 1.20.4+ update in the radar?

**Comment by Cactuxfrombrazil** [comment]
I want one too

**Comment by vico93** [comment]
Forgot to update this issue, @DerpDerpling kindly did at my request a fork of this mod to 1.20.4:

https://github.com/DerpDerpling/ConnectibleChains/tree/1.20.4

I tested and seems to not trigger any errors. I think a release would be done!

**Comment by DerpDerpling** [comment]
I did have to remove some stuff from that port, so it may be a bit buggy

**Comment by legoatoom** [comment]
I have implemented some of the new networking changes and it seems to work.
I will do some more testing when I have time, hopefully this weekend.
If all works, then I will release the update.
When 1.21 is released I hope that time the wait isn't that long.
