### ISSUE TITLE
[Feature Request] Sister Project for Powerlines

### ISSUE THREAD

**Issue by itscurtisnelson** [legoatoom/ConnectibleChains#56]
I see this wonderful chain mod, and I am wondering if there is an easy way to adapt it to become Powerlines?

Perhaps 4x the length, using a simple wire feature

**Comment by legoatoom** [comment]
This sound very similar to Immersive Engineering wires...
I have to decline this request as this would not be easy to adapt that.
And the feature is also very much out of scope of this project.
I would like to keep the mod small.
