### ISSUE TITLE
Duplicate / Overlapping connections

### ISSUE THREAD

**Issue by Qendolin** [legoatoom/ConnectibleChains#6]
The same two fences or walls can be connected multiple times which leads to multiple issues.

1. When a fence is broken or shears are used only one chain item drops.
2. The chain collision entities remain.

How to reproduce:
1. Place two fences, A and B.
2. Connect A to B.
3. Repeat step 2 at least once.
4. Break the chain by destroying either A or B or using shears on either A or B.

Note that the issue does not happen when one connection is formed from A to B and another one from B to A.

Environment:
Minecraft 1.17.1
Connectible Chains 1.2.2

ps: connect A ble would be the correct word (not connect I ble)

**Comment by legoatoom** [comment]
I will try to look at when I have the time and energy. 
Both connectible and connectable are correct.

**Comment by Qendolin** [comment]
I'll try to look into it myself and open a PR but idk if I have time. 
(sure both a fine but -able is 'more' correct)

**Comment by Qendolin** [comment]
The fix is quite easy so I won't make a PR.
In `ChainKnotEntity.attachChain` change the return type to boolean and add these two checks to prevent overlapping connections:
```java
if(this.holdingEntities.containsKey(entity.getId())) return false;
if(entity instanceof ChainKnotEntity knot && knot.holdingEntities.containsKey(this.getId())) {
    return false;
}
```
Also return true at the end of the function.
Then in `ConnectibleChains:66` change
```java
} else {
    knot.attachChain(player, true, 0);
    knot.onPlace();
```
to
```java
} else if(knot.attachChain(player, true, 0)) {
    knot.onPlace();
```

Also in `ChainKnotEntity` you could add this check at the start of `createCollision` but it's not required
```java
if(COLLISION_STORAGE.containsKey(entity.getId())) return;
```
