### ISSUE TITLE
[Bug]: While leading animals, right-clicking with a lead in hand does not attach animals to a fence.

### ISSUE THREAD

**Issue by specialTT** [legoatoom/ConnectibleChains#65]
### Checklist

- [X] I am having issues with the Fabric version.
- [X] I am using the latest version of Connectible Chains.
- [X] I have looked for similar issues.

### MC Version

1.21

### What is the problem?

When an animal is tied, using lead against the fence will not tie the animal to the fence. This behavior is to tie one end of the lead fence to the fence.

**Comment by Psychodeus** [comment]
Yeah me too have this same problem.
