### ISSUE TITLE
Crashes Always

### ISSUE THREAD

**Issue by CaptainX001** [legoatoom/ConnectibleChains#67]
### Checklist

- [X] I am having issues with the Fabric version.
- [X] I am using the latest version of Connectible Chains.
- [x] I have looked for similar issues.

### MC Version

1.21.1

### What is the problem?

I installed Connectible Chains [Fabric] from https://modrinth.com/mod/connectiblechains ; Then when i first opened it everything was working perfect but later on i tried opening it Crashes
[crash-2024-10-06_12.45.14-client.txt](https://github.com/user-attachments/files/17268494/crash-2024-10-06_12.45.14-client.txt)

**Comment by legoatoom** [comment]
Thank you for making an issue. Would you mind sharing your connectible chains config file? The crash log states there might be something wrong with it.

**Comment by legoatoom** [comment]
Closed due to lack of information
