### ISSUE TITLE
[Suggestion] Chain Leads and Lead Chains

### ISSUE THREAD

**Issue by RyanCR03** [legoatoom/ConnectibleChains#9]
You can connect leads from one fence to another and attach chains to hostile mobs. when attaching a chain to a hostile mob it does not stretch beyond a certain point and it will either force the entity forward or force the player to keep the distance

**Comment by legoatoom** [comment]
Decided not to implement this. Chain Leads are not my cup of thee, and Lead Chains I have tried and resulted in conflicts between normal functionality.
